//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpr1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rpr1.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already took this exam! Do you want to retake it?.
        /// </summary>
        internal static string AlreadyTookExam {
            get {
                return ResourceManager.GetString("AlreadyTookExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best answered question.
        /// </summary>
        internal static string BestAnswered {
            get {
                return ResourceManager.GetString("BestAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose option.
        /// </summary>
        internal static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer is number #.
        /// </summary>
        internal static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second correct answer is number #.
        /// </summary>
        internal static string CorrectAnswer2 {
            get {
                return ResourceManager.GetString("CorrectAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct answer must be between 1 and {0} !.
        /// </summary>
        internal static string CorrectAnswerMustBe {
            get {
                return ResourceManager.GetString("CorrectAnswerMustBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct fill-in answer.
        /// </summary>
        internal static string CorrectFillInAnswer {
            get {
                return ResourceManager.GetString("CorrectFillInAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your exam entry key.
        /// </summary>
        internal static string EnterStudentKey {
            get {
                return ResourceManager.GetString("EnterStudentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer.
        /// </summary>
        internal static string EnterYourAnswer {
            get {
                return ResourceManager.GetString("EnterYourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam successfully created!.
        /// </summary>
        internal static string ExamAdded {
            get {
                return ResourceManager.GetString("ExamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exam under this key already exists!.
        /// </summary>
        internal static string ExamExists {
            get {
                return ResourceManager.GetString("ExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam key.
        /// </summary>
        internal static string ExamKey {
            get {
                return ResourceManager.GetString("ExamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You first have to create an Exam B with the same key!.
        /// </summary>
        internal static string ExamNoB {
            get {
                return ResourceManager.GetString("ExamNoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You failed the exam because you&apos;ve selected the wrong answer twice in a row..
        /// </summary>
        internal static string FailedExam {
            get {
                return ResourceManager.GetString("FailedExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You failed the exam. Do you want to see the detailed results?.
        /// </summary>
        internal static string FailedExamDetails {
            get {
                return ResourceManager.GetString("FailedExamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You first have to pass type B exam to take this one!.
        /// </summary>
        internal static string FirstTakeB {
            get {
                return ResourceManager.GetString("FirstTakeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given answer #.
        /// </summary>
        internal static string GivenAnswer {
            get {
                return ResourceManager.GetString("GivenAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be younger than 26 in order to take this exam!.
        /// </summary>
        internal static string LessThan26 {
            get {
                return ResourceManager.GetString("LessThan26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose either the Professor or the Student interface:.
        /// </summary>
        internal static string MenuNoteChooseSubinterface {
            get {
                return ResourceManager.GetString("MenuNoteChooseSubinterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new exam type A.
        /// </summary>
        internal static string MenuOptionCreateNewExamA {
            get {
                return ResourceManager.GetString("MenuOptionCreateNewExamA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new exam type B.
        /// </summary>
        internal static string MenuOptionCreateNewExamB {
            get {
                return ResourceManager.GetString("MenuOptionCreateNewExamB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load exam and student data from saved file.
        /// </summary>
        internal static string MenuOptionLoadData {
            get {
                return ResourceManager.GetString("MenuOptionLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string MenuOptionProfessor {
            get {
                return ResourceManager.GetString("MenuOptionProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save exam and student data to file.
        /// </summary>
        internal static string MenuOptionSaveData {
            get {
                return ResourceManager.GetString("MenuOptionSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string MenuOptionStudent {
            get {
                return ResourceManager.GetString("MenuOptionStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student list.
        /// </summary>
        internal static string MenuOptionStudentList {
            get {
                return ResourceManager.GetString("MenuOptionStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take an exam.
        /// </summary>
        internal static string MenuOptionTakeExams {
            get {
                return ResourceManager.GetString("MenuOptionTakeExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View exam questions.
        /// </summary>
        internal static string MenuOptionViewExamQuestions {
            get {
                return ResourceManager.GetString("MenuOptionViewExamQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View exam results.
        /// </summary>
        internal static string MenuOptionViewExamResults {
            get {
                return ResourceManager.GetString("MenuOptionViewExamResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View exam list.
        /// </summary>
        internal static string MenuOptionViewExams {
            get {
                return ResourceManager.GetString("MenuOptionViewExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View stats.
        /// </summary>
        internal static string MenuOptionViewGlobalStats {
            get {
                return ResourceManager.GetString("MenuOptionViewGlobalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my exams.
        /// </summary>
        internal static string MenuOptionViewStudentExams {
            get {
                return ResourceManager.GetString("MenuOptionViewStudentExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have an entry key, just type anything..
        /// </summary>
        internal static string NoEntryKey {
            get {
                return ResourceManager.GetString("NoEntryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t entered anything! Please try again..
        /// </summary>
        internal static string NoInputError {
            get {
                return ResourceManager.GetString("NoInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one took this exam.
        /// </summary>
        internal static string NoOneTookExam {
            get {
                return ResourceManager.GetString("NoOneTookExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No student with that key is registered.
        /// </summary>
        internal static string NoSuchKey {
            get {
                return ResourceManager.GetString("NoSuchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date format!.
        /// </summary>
        internal static string NotADate {
            get {
                return ResourceManager.GetString("NotADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t entered a number or it doesn&apos;t satisfy certain parameters!.
        /// </summary>
        internal static string NotANumberOrNotValidated {
            get {
                return ResourceManager.GetString("NotANumberOrNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t entered a string or it doesn&apos;t satisfy certain parameters!.
        /// </summary>
        internal static string NotAStringOrNotValidated {
            get {
                return ResourceManager.GetString("NotAStringOrNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not passed.
        /// </summary>
        internal static string NotPassedWord {
            get {
                return ResourceManager.GetString("NotPassedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You passed the exam. Do you want to see the detailed results?.
        /// </summary>
        internal static string PassedExam {
            get {
                return ResourceManager.GetString("PassedExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed with {0} correct answers.
        /// </summary>
        internal static string PassedWithN {
            get {
                return ResourceManager.GetString("PassedWithN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string PassedWord {
            get {
                return ResourceManager.GetString("PassedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study years&apos; percentage in total passed exams.
        /// </summary>
        internal static string PercentagePerYear {
            get {
                return ResourceManager.GetString("PercentagePerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question #.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is either longer than 10 words or there&apos;s a similar question already!.
        /// </summary>
        internal static string QuestionNotValidated {
            get {
                return ResourceManager.GetString("QuestionNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is either longer than 10 words, or there&apos;s a similar question - or there&apos;s a same question in exam type B!.
        /// </summary>
        internal static string QuestionNotValidatedA {
            get {
                return ResourceManager.GetString("QuestionNotValidatedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth (dd.mm.yyyy format).
        /// </summary>
        internal static string StudentBirthday {
            get {
                return ResourceManager.GetString("StudentBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered. Your key is {0}. Please write it down somewhere!.
        /// </summary>
        internal static string StudentCreated {
            get {
                return ResourceManager.GetString("StudentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of faculty.
        /// </summary>
        internal static string StudentFaculty {
            get {
                return ResourceManager.GetString("StudentFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string StudentFirstName {
            get {
                return ResourceManager.GetString("StudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string StudentLastName {
            get {
                return ResourceManager.GetString("StudentLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of study.
        /// </summary>
        internal static string StudentStudyYear {
            get {
                return ResourceManager.GetString("StudentStudyYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total passed.
        /// </summary>
        internal static string TotalPassed {
            get {
                return ResourceManager.GetString("TotalPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That exam entry key does not exist. Do you want to register as a new student in order to get the entry key?.
        /// </summary>
        internal static string WantToRegister {
            get {
                return ResourceManager.GetString("WantToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst answered question.
        /// </summary>
        internal static string WorstAnswered {
            get {
                return ResourceManager.GetString("WorstAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string YearWord {
            get {
                return ResourceManager.GetString("YearWord", resourceCulture);
            }
        }
    }
}
